apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: postgresql
type: Opaque
data:
  # The values must be base64 encoded
  # In a real scenario, these are passed via --set or a secrets file
  password: {{ .Values.postgresPassword | b64enc | quote }}
  postgres-password: {{ .Values.postgresAdminPassword | default .Values.postgresPassword | b64enc | quote }}